package com.curso.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-06-10T14:25:24.115+02:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://ws.curso.com/", name = "ServicioCoches")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicioCoches {

    @Action(input = "http://ws.curso.com/ServicioCoches/insertarRequest", output = "http://ws.curso.com/ServicioCoches/insertarResponse")
    @RequestWrapper(localName = "insertar", targetNamespace = "http://ws.curso.com/", className = "com.curso.ws.Insertar")
    @WebMethod
    @ResponseWrapper(localName = "insertarResponse", targetNamespace = "http://ws.curso.com/", className = "com.curso.ws.InsertarResponse")
    public void insertar(
        @WebParam(name = "arg0", targetNamespace = "")
        com.curso.ws.Coche arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.curso.com/ServicioCoches/listarTodosRequest", output = "http://ws.curso.com/ServicioCoches/listarTodosResponse")
    @RequestWrapper(localName = "listarTodos", targetNamespace = "http://ws.curso.com/", className = "com.curso.ws.ListarTodos")
    @WebMethod
    @ResponseWrapper(localName = "listarTodosResponse", targetNamespace = "http://ws.curso.com/", className = "com.curso.ws.ListarTodosResponse")
    public java.util.List<com.curso.ws.Coche> listarTodos();
}
