
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.curso.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-06-10T14:25:24.096+02:00
 * Generated source version: 2.7.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "ServicioCoches",
                      portName = "ServicioCochesPort",
                      targetNamespace = "http://ws.curso.com/",
                      wsdlLocation = "http://localhost:8081/ServicioCoches?wsdl",
                      endpointInterface = "com.curso.ws.ServicioCoches")
                      
public class ServicioCochesImpl implements ServicioCoches {

    private static final Logger LOG = Logger.getLogger(ServicioCochesImpl.class.getName());

    /* (non-Javadoc)
     * @see com.curso.ws.ServicioCoches#insertar(com.curso.ws.Coche  arg0 )*
     */
    public void insertar(com.curso.ws.Coche arg0) { 
        LOG.info("Executing operation insertar");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.curso.ws.ServicioCoches#listarTodos(*
     */
    public java.util.List<com.curso.ws.Coche> listarTodos() { 
        LOG.info("Executing operation listarTodos");
        try {
            java.util.List<com.curso.ws.Coche> _return = new java.util.ArrayList<com.curso.ws.Coche>();
            com.curso.ws.Coche _returnVal1 = new com.curso.ws.Coche();
            _returnVal1.setMarca("Marca-932064447");
            _returnVal1.setMatricula("Matricula306903047");
            _returnVal1.setModelo("Modelo-161231565");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
