package com.curso.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-06-10T14:25:24.126+02:00
 * Generated source version: 2.7.16
 * 
 */
@WebServiceClient(name = "ServicioCoches", 
                  wsdlLocation = "http://localhost:8081/ServicioCoches?wsdl",
                  targetNamespace = "http://ws.curso.com/") 
public class ServicioCoches_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.curso.com/", "ServicioCoches");
    public final static QName ServicioCochesPort = new QName("http://ws.curso.com/", "ServicioCochesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/ServicioCoches?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioCoches_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/ServicioCoches?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioCoches_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioCoches_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioCoches_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioCoches_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioCoches_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioCoches_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicioCoches
     */
    @WebEndpoint(name = "ServicioCochesPort")
    public ServicioCoches getServicioCochesPort() {
        return super.getPort(ServicioCochesPort, ServicioCoches.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioCoches
     */
    @WebEndpoint(name = "ServicioCochesPort")
    public ServicioCoches getServicioCochesPort(WebServiceFeature... features) {
        return super.getPort(ServicioCochesPort, ServicioCoches.class, features);
    }

}
