
package com.curso.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-06-10T14:25:24.028+02:00
 * Generated source version: 2.7.16
 * 
 */
public final class ServicioCoches_ServicioCochesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.curso.com/", "ServicioCoches");

    private ServicioCoches_ServicioCochesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServicioCoches_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServicioCoches_Service ss = new ServicioCoches_Service(wsdlURL, SERVICE_NAME);
        ServicioCoches port = ss.getServicioCochesPort();  
        
        {
        System.out.println("Invoking insertar...");
        com.curso.ws.Coche _insertar_arg0 = new com.curso.ws.Coche();
        _insertar_arg0.setMarca("Marca-230053720");
        _insertar_arg0.setMatricula("Matricula-580836673");
        _insertar_arg0.setModelo("Modelo1839126436");
        port.insertar(_insertar_arg0);


        }
        {
        System.out.println("Invoking listarTodos...");
        java.util.List<com.curso.ws.Coche> _listarTodos__return = port.listarTodos();
        System.out.println("listarTodos.result=" + _listarTodos__return);


        }

        System.exit(0);
    }

}
